# This image contains Fake Service Consul and Envoy, it can be used to simulate a Virtual Machine containing the Consul Agent
# and Envoy running as Daemon processes.
FROM nicholasjackson/consul-envoy:v1.10.7-v1.18.3 as base

# Setup bash and supervisord etc
RUN apt-get update && \
    apt-get install -y supervisor && \
    rm -rf /var/lib/apt/lists/*
    
RUN sed -i 's/\/bin\/ash/\/bin\/bash/g' /etc/passwd

COPY entrypoint.sh /entrypoint.sh
COPY prestart.sh /prestart.sh

RUN chmod +x /entrypoint.sh
RUN chmod +x /prestart.sh

# Setup the supervisor d file
COPY fake-service.conf /etc/supervisor/conf.d/fake-service.conf


# Copy AMD binaries
FROM base AS image-amd64-

COPY bin/linux/amd64/fake-service /app/fake-service
RUN chmod +x /app/fake-service

# Copy Arm 8 binaries
FROM base AS image-arm64-

COPY bin/linux/arm64/fake-service /app/fake-service
RUN chmod +x /app/fake-service

FROM image-${TARGETARCH}-${TARGETVARIANT}

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG BUILDPLATFORM
ARG BUILDARCH

RUN echo "I am running on $BUILDPLATFORM, building for $TARGETPLATFORM $TARGETARCH $TARGETVARIANT"  

# set default env vars so supervisor
# does not crash on start
ENV CONSUL_HTTP_ADDR=localhost:8500
ENV CONSUL_SERVER=localhost
ENV CONSUL_DATACENTER=dc1
ENV SERVICE_ID=null
ENV CONSUL_RETRY_INTERVAL=5s 
ENV PRESTART_FILE=/prestart.sh

# add default config folder
RUN mkdir /config

# data directory for Consul
RUN mkdir -p /etc/consul

# Run supervisord in blocking mode
ENTRYPOINT ["/usr/bin/supervisord"]
CMD ["-c", "/etc/supervisor/supervisord.conf", "-n"]
