# This image contains Fake Service Consul and Envoy, it can be used to simulate a Virtual Machine containing the Consul Agent
# and Envoy running as Daemon processes.
FROM nicholasjackson/consul-envoy:v1.8.0-v0.12.4

# Setup bash and supervisord etc
RUN apk add --update bash supervisor curl vim jq 
RUN sed -i 's/\/bin\/ash/\/bin\/bash/g' /etc/passwd

RUN mkdir -p /etc/supervisor.d/

COPY entrypoint.sh /entrypoint.sh

# Setup the supervisor d file
COPY fake-service.ini /etc/supervisor.d/fake-service.ini
RUN chmod +x /entrypoint.sh

# Run supervisord
RUN sed -i 's/;nodaemon=false/nodaemon=true/g' /etc/supervisord.conf

# add fake service
RUN mkdir app
COPY ./bin/fake-service-linux /app/fake-service

# set default env vars so supervisor
# does not crash on start
ENV CONSUL_HTTP_ADDR=localhost:8500
ENV CONSUL_SERVER=localhost
ENV CONSUL_DATACENTER=dc1
ENV SERVICE_ID=null
ENV CONSUL_RETRY_INTERVAL=5s 

# add default config folder
RUN mkdir /config

# data directory for Consul
RUN mkdir -p /etc/consul

ENTRYPOINT ["/usr/bin/supervisord"]
CMD ["-c", "/etc/supervisord.conf"]
